name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        brew install libyaml curl

    - name: Configure and build with CMake
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_PREFIX_PATH="/usr/local" ../turbo
        make

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Install the package
      run: |
        cd build
        sudo make install  

    - name: Create distribution package
      run: |
        cd build
        make package 
